# syntax=docker/dockerfile:1
FROM node:alpine AS etap1
ENV NODE_OPTIONS=--openssl-legacy-provider
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx AS etap2
COPY --from=0 /app/build /usr/share/nginx/html
